steps:
  - id: Build image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA
      - .

  - id: Push image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA

  - id: Deploy Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --port=8080
      - --set-env-vars=API_BASE_URL=${_API_BASE_URL},USE_MOCK=false

substitutions:
  _REGION: europe-west1
  _SERVICE: dmc-dataloader-console
  _REPOSITORY: dmc
  _API_BASE_URL: ''

options:
  logging: CLOUD_LOGGING_ONLY
